### ISSUE TITLE
Add-on is not loaded

### ISSUE THREAD

**Issue by CyrilleB79** [ruifontes/tesseractOCR#7]
Hi Rui

I have just installed this add-on but it cannot load.

### Log error:

```
ERROR - globalPluginHandler.listPlugins (13:11:00.475) - MainThread (18116):
Error importing global plugin tesseractOCR
Traceback (most recent call last):
  File "C:\Users\CB232690\AppData\Roaming\nvda\addons\tesseractOCR\globalPlugins\tesseractOCR\vars.py", line 111, in <module>
    if config.conf["tesseractOCR"]["device"]:
  File "config\__init__.pyc", line 1125, in __getitem__
KeyError: 'device'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "globalPluginHandler.pyc", line 23, in listPlugins
  File "importlib\__init__.pyc", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\CB232690\AppData\Roaming\nvda\addons\tesseractOCR\globalPlugins\tesseractOCR\__init__.py", line 35, in <module>
    from .vars import *
  File "C:\Users\CB232690\AppData\Roaming\nvda\addons\tesseractOCR\globalPlugins\tesseractOCR\vars.py", line 114, in <module>
    scanner = WIAList[0]
NameError: name 'WIAList' is not defined

```

### To reproduce

Maybe you can reproduce if you unplug your scanner and if you run a clean instance of NVDA without any value related to this add-on in the config.

**Comment by ruifontes** [comment]
Already corrected in next version to be published soon.
By now, if you want, download version 2023.05.05 through:
https://www.dropbox.com/s/tkj7n5gpfa2g1xw/tesseractOCR_2023.05.05.nvda-addon?dl=1
